version: '3.3'
services:
  jupyter:
    environment:
      - SHELL=/bin/bash
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - type : bind
       source: ./
       target: /app/
    hostname:
        automl
    ports:
      - "10001:10000"
    command: jupyter lab --notebook-dir=/app --ip="0.0.0.0" --port=10000 --no-browser --allow-root
    container_name: project_name
